#!/usr/bin/env python

# Placeholder: this is the script that will
# 1. configure the node
# 2. run the script (argv1)
# 3. profit?

# Run configuration steps here.  Mount file systems, load core modules, that
# sort of thing

# Read script from argument.  Assume argument list is 
